describe('Upload Coindrop avatar', () => {
    before(() => {
      cy.logout();
      cy.login();
    });

    // This test has several shortcomings:
    // - Not waiting on any network requests (hard to identify/intercept the various Firestore requests)
    // - Cache is being mutated locally with SWR so waiting for UI to change doesn't mean database actually changed
    // - Rendered image is not verified (uploaded image will not match optimized image generated by next/image, and image does not have any name attributes that can be verified?)
    it('Upload Coindrop avatar', () => {
        const testID_rgpyfo = "rgpyfo";
        const testCoindropName = `cy-${testID_rgpyfo}`;
        cy.callFirestore("delete", `piggybanks/${testCoindropName}`);
        cy.callFirestore("set", `piggybanks/${testCoindropName}`, {
            owner_uid: Cypress.env("TEST_UID"),
        });
        cy.visit(`/${testCoindropName}`);
        cy.contains('This Coindrop has not been set up yet');
        cy.get('#configure-coindrop-button')
            .click();
        cy.get('[data-cy="avatar-placeholder"]');
        cy.get('[data-cy="coindrop-avatar"]').should('not.exist');
        cy.contains('Upload image');
        cy.get('[data-cy="file-input"]')
            .attachFile('test-avatar.png');
        cy.get('[data-cy="coindrop-avatar"]', { timeout: 15000 });
        cy.get('[data-cy="avatar-placeholder"]').should('not.exist');
        cy.contains('Upload new image');
        cy.get('[data-cy="remove-image-btn"]')
            .click();
        cy.get('[data-cy="avatar-placeholder"]');
        cy.get('[data-cy="coindrop-avatar"]').should('not.exist');
    });
});

export {};
